#!/bin/bash

# System monitor daemon service

# Requires: conky

set -eu

if (( $# < 1 )); then
	echo "usage: conkymon start [interval]" >&2
	echo "       conkymon stop" >&2
	exit 1
fi

conkyrc='
conky.config = {
 cpu_avg_samples = 6,
 no_buffers = true,
 own_window = true,
 out_to_stderr = true
}
conky.text = [[
[conky] up: $uptime | cpu: $cpu% | mem: $mem ($memperc%) | disk: ${fs_used} (${fs_used_perc}%)
]]
'

pidfile=/var/run/user/$UID/conkymon.pid

case $1 in
	start)
		shift
		# set update interval (in seconds)
		if (( $# >=1 )); then
			interval=$1
		else
			interval=10
		fi

		# start conky in background
		if [[ ! -f $pidfile ]]; then
			conky -c <(echo $conkyrc) -u $interval &
			echo $! > $pidfile
		else
			echo "Error: conkymon is already running (pid = $(cat $pidfile))"
			exit 1
		fi
		;;
	stop)
		shift
		kill $(cat $pidfile)
		rm $pidfile
		;;
	*)
		echo "Error: unrecognized command $1"
		exit 1
		;;
esac
