#!/bin/bash

# System monitor daemon service
# 
# interval    update interval in seconds
# mountpoint  file system mount point to monitor for disk usage
#
# Requires: conky
# Author:   David J. H. Shih <djh.shih@gmail.com>
# License:  GPLv3

set -eu

if (( $# < 1 )); then
	echo "usage: conkymon start [interval] [mountpoint]" >&2
	echo "       conkymon stop" >&2
	exit 1
fi


piddir=/var/run/user/$UID/
pidfile=$piddir/conkymon.pid

case $1 in
	start)
		shift

		# set monitor update interval (in seconds)
		if (( $# >=1 )); then
			interval=$1
			shift
		else
			interval=60
		fi

		# set mount point for filesystem monitoring
		if (( $# >= 1 )); then
			mountpoint=$1
			shift
		else
			mountpoint='/'
		fi

		conkyrc="
			conky.config = {
			 no_buffers = true,
			 out_to_console = false,
			 out_to_stderr = true
			}
			conky.text = [[
			[conky] up: \$uptime | cpu: \$cpu% | mem: \$mem (\$memperc%) | disk: \${fs_used $mountpoint} (\${fs_used_perc $mountpoint}%)
			]]
		"

		# start conky in background
		if [[ ! -f $pidfile ]]; then
			conky -c <(echo $conkyrc) -u $interval &
			mkdir -p $piddir
			echo $! > $pidfile
		else
			echo "Error: conkymon is already running (pid = $(cat $pidfile))"
			exit 1
		fi
		;;
	stop)
		shift
		kill $(cat $pidfile) || true
		rm $pidfile
		;;
	*)
		echo "Error: unrecognized command $1"
		exit 1
		;;
esac
